"""add tricky puzzles index to puzzle_stats

Revision ID: 02cb658e598b
Revises: b7a2c7d2b7c9
Create Date: 2026-02-02 16:17:57.621968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "02cb658e598b"
down_revision: Union[str, Sequence[str], None] = "b7a2c7d2b7c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_puzzle_stats_tricky_puzzles",
        "puzzle_stats",
        ["username", "fail_count", "last_reviewed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_puzzle_stats_tricky_puzzles", table_name="puzzle_stats")
    # ### end Alembic commands ###
