"""create_rating_snapshots_table

Revision ID: 18d35c5a5d79
Revises: ab235ce26ed5
Create Date: 2026-01-31 12:00:21.207270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "18d35c5a5d79"
down_revision: Union[str, Sequence[str], None] = "ab235ce26ed5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("time_control", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rating_snapshots_session_id"),
        "rating_snapshots",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rating_snapshots_username"),
        "rating_snapshots",
        ["username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rating_snapshots_username"), table_name="rating_snapshots")
    op.drop_index(op.f("ix_rating_snapshots_session_id"), table_name="rating_snapshots")
    op.drop_table("rating_snapshots")
    # ### end Alembic commands ###
