"""Add title and motif to puzzle_stats

Revision ID: 24f9ca599cee
Revises: 9a8d0c56273f
Create Date: 2026-01-30 18:31:50.772930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f9ca599cee'
down_revision: Union[str, Sequence[str], None] = '9a8d0c56273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle_stats', sa.Column('title', sa.String(), nullable=True))
    op.add_column('puzzle_stats', sa.Column('primary_motif', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle_stats', 'primary_motif')
    op.drop_column('puzzle_stats', 'title')
    # ### end Alembic commands ###
