"""Add training sessions and session tracking

Revision ID: 35523bdeba3e
Revises: 24f9ca599cee
Create Date: 2026-01-30 20:23:25.894794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35523bdeba3e"
down_revision: Union[str, Sequence[str], None] = "24f9ca599cee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("requested_n", sa.Integer(), nullable=False),
        sa.Column("pass_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fail_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_time_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_created_at"),
        "training_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_sessions_username"),
        "training_sessions",
        ["username"],
        unique=False,
    )
    op.add_column("puzzle_reviews", sa.Column("session_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_puzzle_reviews_session_id"),
        "puzzle_reviews",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_puzzle_reviews_session_id"), table_name="puzzle_reviews")
    op.drop_column("puzzle_reviews", "session_id")
    op.drop_index(op.f("ix_training_sessions_username"), table_name="training_sessions")
    op.drop_index(
        op.f("ix_training_sessions_created_at"), table_name="training_sessions"
    )
    op.drop_table("training_sessions")
    # ### end Alembic commands ###
