"""add_params_column

Revision ID: ee3cd9312dc0
Revises: 5b5261f7d4ab
Create Date: 2026-01-30 10:38:37.639844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ee3cd9312dc0"
down_revision: Union[str, Sequence[str], None] = "5b5261f7d4ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("params", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "params")
    # ### end Alembic commands ###
