name: Frontend CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/ci-frontend.yaml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/ci-frontend.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: apps/web/package-lock.json

    - name: Install dependencies
      working-directory: ./apps/web
      run: npm ci

    - name: Lint
      working-directory: ./apps/web
      run: npm run lint

    - name: Test
      working-directory: ./apps/web
      run: npm run test -- --run

    - name: Build
      working-directory: ./apps/web
      run: npm run build
